# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61b1a0c50d8f3862344b062c412e4ce8d787aca9a3203bb0d4a3a6243109578e466ceef39afc3c821f61da8cf3e4d4a46e6dd8a7cc242e7a1a75c42db6c5e748

test:
  secret_key_base: 27543d042aa33e933739b4415d34a9c5dbcf05050b32996958d2df8e9ab3c42a43d49067017ce9575e899613f32f6b6de6b24a3863df5d7d0f34143bc3c106b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
